apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umami-prod
spec:
  project: default
  source:
    repoURL: https://github.com/instructlab/ui.git
    path: deploy/k8s/overlays/openshift/umami/prod
    targetRevision: main
  destination:
    namespace: umami
    name: instructlab-ui-prod
  syncPolicy:
    automated:
      selfHeal: true

