apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instructlab
resources:
  - service.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: ui
      app.kubernetes.io/name: ui
