contact_links:
  - name: ❓ Help and Support Slack Channel
    url: https://app.slack.com/client/T06TXCT5SNM
    about: Please ask and answer questions here. 🏥
  - name: ❓ Help and Support Discord Channel
    url: https://discord.gg/Fa6tRapUZ2
    about: Please ask and answer questions here. 🏥
