apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: umami
  labels:
    name: umami
spec:
  host: umami.qa.instructlab.ui
  port:
    targetPort: 3001
  tls:
    termination: edge
  to:
    kind: Service
    name: umami
    weight: 100
  wildcardPolicy: None

