apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: umami
resources:
  - ../../../../base/umami
  - umami-route.yaml
patches:
  - target:
      kind: Deployment
      name: umami
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.redhat.io/rhel9/postgresql-15:9.5-1733127512
      - op: replace
        path: /spec/template/spec/containers/0/env/0/name
        value: POSTGRESQL_DATABASE
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/key
        value: POSTGRESQL_DATABASE
      - op: replace
        path: /spec/template/spec/containers/0/env/1/name
        value: POSTGRESQL_USER
      - op: replace
        path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/key
        value: POSTGRESQL_USER
      - op: replace
        path: /spec/template/spec/containers/0/env/2/name
        value: POSTGRESQL_PASSWORD
      - op: replace
        path: /spec/template/spec/containers/0/env/2/valueFrom/secretKeyRef/key
        value: POSTGRESQL_PASSWORD
