apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instructlab
resources:
  - ../../../base
  - issuer.yaml
  - certificate.yaml
  - prod.env.sealedsecret.yaml
patches:
  - target:
      kind: Ingress
      name: ui
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/pathType
        value: ImplementationSpecific
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: ''
      - op: replace
        path: /spec/rules/0/host
        value: ui.instructlab.ai
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ui.instructlab.ai

  - target:
      kind: Deployment
      name: ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: prod.env
images:
  - name: quay.io/instructlab-ui/ui
    newTag: v1.0.0-beta.3
  - name: quay.io/instructlab-ui/pathservice
    newTag: v1.0.0-beta.3
