apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instructlab
resources:
  - ../../../base
  - ../common
  - issuer.yaml
  - certificate.yaml
  - qa.env.sealedsecret.yaml
patches:
  - target:
      kind: Ingress
      name: ui
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/pathType
        value: ImplementationSpecific
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: ''
      - op: replace
        path: /spec/rules/0/host
        value: qa.ui.instructlab.ai
      - op: replace
        path: /spec/tls/0/hosts/0
        value: qa.ui.instructlab.ai
  - target:
      kind: Deployment
      name: ui
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: qa.env
      - op: add 
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          exec:
            command:
              - sh
              - -c
              - "/opt/app-root/src/src/healthcheck-probe.sh"
          initialDelaySeconds: 5
          periodSeconds: 10
      - op: add
        path: /spec/template/spec/containers/-
        value:
          name: model-endpoint-healthcheck-sidecar
          image: quay.io/instructlab-ui/healthcheck-sidecar
          imagePullPolicy: Always # until image lands in quay cannot use pullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: qa.env
images:
  - name: quay.io/instructlab-ui/ui
    newTag: pr-435
  - name: quay.io/instructlab-ui/pathservice
    newTag: pr-435
  - name: quay.io/instructlab-ui/healthcheck-sidecar
    newTag: main
