apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel9/postgresql-15:9.5-1733127512
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: umami-secret
                  key: POSTGRESQL_DATABASE
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: umami-secret
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: umami-secret
                  key: POSTGRESQL_PASSWORD
          ports:
            - containerPort: 5432
              name: postgres
          livenessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
        - name: umami
          image: ghcr.io/umami-software/umami:postgresql-latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: umami-secret
                  key: DATABASE_URL
            - name: DATABASE_TYPE
              value: postgresql
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: umami-secret
                  key: APP_SECRET
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: umami-postgresql-db-data
