apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: umami
resources:
  - deployment.yaml
  - namespace.yaml
  - postgresql-pvc.yaml
  - postgresql-service.yaml
  - umami-service.yaml
labels:
  - includeSelectors: true
    pairs:
      app: umami
      app.kubernetes.io/component: umami
      app.kubernetes.io/instance: umami
      app.kubernetes.io/name: umami
      app.kubernetes.io/part-of: umami
