apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: umami
resources:
  - deployment.yaml
  - namespace.yaml
  - postgresql-pvc.yaml
  - postgresql-service.yaml
  - umami-service.yaml
