apiVersion: v1
kind: Service
metadata:
  name: umami-db
  labels:
    app.kubernetes.io/component: umami-postgresql
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app.kubernetes.io/name: umami
