apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umami-postgresql-db-data
  labels:
    app: umami
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
