---
apiVersion: v1
kind: Service
metadata:
  name: umami
  labels:
    app.kubernetes.io/component: umami-web
spec:
  ports:
    - name: web
      port: 3001
  selector:
    app.kubernetes.io/name: umami
  type: ClusterIP
