name: Cherry-Pick into release-1.0 branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cherry_pick:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Cherry-pick commit
        run: |
          git checkout release-1.0
          git cherry-pick ${{ github.event.pull_request.merge_commit_sha }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: cherry-pick-${{ github.event.pull_request.number }}
          base: release-1.0
          title: 'Cherry-pick: Add commit to  release-1.0 ${{ github.event.pull_request.title }}'
          body: 'Automatically cherry-picked commit from main branch'
